# Generated by Django 4.0.2 on 2022-03-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=30)),
                ('gia', models.CharField(max_length=30)),
                ('mota', models.CharField(max_length=30)),
            ],
        ),
    ]
