# Generated by Django 4.0.2 on 2022-03-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_anh'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=30)),
                ('mota', models.CharField(max_length=255)),
            ],
        ),
    ]
