# Generated by Django 4.0.2 on 2022-04-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='cate_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_post_name', models.CharField(max_length=255)),
                ('cate_post_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=255)),
                ('comment_content', models.CharField(max_length=255)),
                ('product_id', models.IntegerField(default=None)),
                ('comment_parent_id', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=255)),
                ('cus_email', models.CharField(max_length=255)),
                ('cus_phone', models.CharField(max_length=30)),
                ('cus_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=None)),
                ('gallery_image', models.ImageField(default=None, upload_to='images')),
                ('gallery_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.IntegerField(default=None)),
                ('shipping_id', models.IntegerField(default=None)),
                ('order_code', models.CharField(max_length=50)),
                ('order_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50)),
                ('product_id', models.IntegerField(default=None)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.IntegerField()),
                ('product_sale_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=255)),
                ('post_content', models.CharField(max_length=255)),
                ('post_image', models.ImageField(default=None, upload_to='images')),
                ('post_author', models.CharField(max_length=255)),
                ('cate_post_id', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=None)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=255)),
                ('ship_email', models.CharField(max_length=255)),
                ('ship_phone', models.CharField(max_length=30)),
                ('ship_address', models.CharField(max_length=30)),
                ('ship_note', models.CharField(max_length=255)),
                ('ship_method', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='anh',
            new_name='pro_image',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='mota',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='ten',
        ),
        migrations.RemoveField(
            model_name='category',
            name='mota',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ten',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gia',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mota',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ten',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_desc',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='cate_desc',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='cate_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_desc',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_quantity',
            field=models.IntegerField(default=None),
        ),
    ]
