# Generated by Django 4.0.2 on 2022-04-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_brand_id_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='bra',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='cate',
        ),
    ]
