# Generated by Django 4.0.2 on 2022-04-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_brand_product_bra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bra',
            new_name='brand_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cate',
            new_name='category_id',
        ),
    ]
