# Generated by Django 4.0.2 on 2022-04-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_bra_product_brand_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.IntegerField(default=None),
        ),
    ]
