# Generated by Django 4.0.2 on 2022-04-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_brand_id_alter_product_category_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
