# Generated by Django 4.0.2 on 2022-04-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(default=None, max_length=255)),
                ('pro_price', models.IntegerField(default=None)),
                ('pro_quantity', models.IntegerField(default=None)),
                ('pro_desc', models.CharField(default=None, max_length=255)),
                ('pro_image', models.ImageField(default=None, upload_to='images')),
                ('category_id', models.IntegerField(default=None)),
                ('brand_id', models.IntegerField(default=None)),
            ],
        ),
    ]
