# Generated by Django 4.0.2 on 2022-04-15 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_gallery_product_id_alter_rating_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cate_post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cate_post'),
        ),
    ]
